# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/settings/master/form_settings.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.enums import form_pb2 as pogoprotos_dot_enums_dot_form__pb2
from pogoprotos.enums import pokemon_id_pb2 as pogoprotos_dot_enums_dot_pokemon__id__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/settings/master/form_settings.proto',
  package='pogoprotos.settings.master',
  syntax='proto3',
  serialized_pb=_b('\n.pogoprotos/settings/master/form_settings.proto\x12\x1apogoprotos.settings.master\x1a\x1bpogoprotos/enums/form.proto\x1a!pogoprotos/enums/pokemon_id.proto\"c\n\x0c\x46ormSettings\x12,\n\x07pokemon\x18\x01 \x01(\x0e\x32\x1b.pogoprotos.enums.PokemonId\x12%\n\x05\x66orms\x18\x02 \x03(\x0e\x32\x16.pogoprotos.enums.Formb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_enums_dot_form__pb2.DESCRIPTOR,pogoprotos_dot_enums_dot_pokemon__id__pb2.DESCRIPTOR,])




_FORMSETTINGS = _descriptor.Descriptor(
  name='FormSettings',
  full_name='pogoprotos.settings.master.FormSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pokemon', full_name='pogoprotos.settings.master.FormSettings.pokemon', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='forms', full_name='pogoprotos.settings.master.FormSettings.forms', index=1,
      number=2, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=241,
)

_FORMSETTINGS.fields_by_name['pokemon'].enum_type = pogoprotos_dot_enums_dot_pokemon__id__pb2._POKEMONID
_FORMSETTINGS.fields_by_name['forms'].enum_type = pogoprotos_dot_enums_dot_form__pb2._FORM
DESCRIPTOR.message_types_by_name['FormSettings'] = _FORMSETTINGS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FormSettings = _reflection.GeneratedProtocolMessageType('FormSettings', (_message.Message,), dict(
  DESCRIPTOR = _FORMSETTINGS,
  __module__ = 'pogoprotos.settings.master.form_settings_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.settings.master.FormSettings)
  ))
_sym_db.RegisterMessage(FormSettings)


# @@protoc_insertion_point(module_scope)
