# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/platform.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/platform.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_pb=_b('\n\x1fpogoprotos/enums/platform.proto\x12\x10pogoprotos.enums*\x88\x01\n\x08Platform\x12\x12\n\x0ePLATFORM_UNSET\x10\x00\x12\x10\n\x0cPLATFORM_IOS\x10\x01\x12\x14\n\x10PLATFORM_ANDROID\x10\x02\x12\x10\n\x0cPLATFORM_OSX\x10\x03\x12\x14\n\x10PLATFORM_WINDOWS\x10\x04\x12\x18\n\x14PLATFORM_APPLE_WATCH\x10\x05\x62\x06proto3')
)

_PLATFORM = _descriptor.EnumDescriptor(
  name='Platform',
  full_name='pogoprotos.enums.Platform',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PLATFORM_UNSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLATFORM_IOS', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLATFORM_ANDROID', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLATFORM_OSX', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLATFORM_WINDOWS', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLATFORM_APPLE_WATCH', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=54,
  serialized_end=190,
)
_sym_db.RegisterEnumDescriptor(_PLATFORM)

Platform = enum_type_wrapper.EnumTypeWrapper(_PLATFORM)
PLATFORM_UNSET = 0
PLATFORM_IOS = 1
PLATFORM_ANDROID = 2
PLATFORM_OSX = 3
PLATFORM_WINDOWS = 4
PLATFORM_APPLE_WATCH = 5


DESCRIPTOR.enum_types_by_name['Platform'] = _PLATFORM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
