# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/enums/pokemon_movement_type.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/enums/pokemon_movement_type.proto',
  package='pogoprotos.enums',
  syntax='proto3',
  serialized_pb=_b('\n,pogoprotos/enums/pokemon_movement_type.proto\x12\x10pogoprotos.enums*\x81\x02\n\x13PokemonMovementType\x12\x1f\n\x1bPOKEMON_ENC_MOVEMENT_STATIC\x10\x00\x12\x1d\n\x19POKEMON_ENC_MOVEMENT_JUMP\x10\x01\x12!\n\x1dPOKEMON_ENC_MOVEMENT_VERTICAL\x10\x02\x12 \n\x1cPOKEMON_ENC_MOVEMENT_PSYCHIC\x10\x03\x12!\n\x1dPOKEMON_ENC_MOVEMENT_ELECTRIC\x10\x04\x12\x1f\n\x1bPOKEMON_ENC_MOVEMENT_FLYING\x10\x05\x12!\n\x1dPOKEMON_ENC_MOVEMENT_HOVERING\x10\x06\x62\x06proto3')
)

_POKEMONMOVEMENTTYPE = _descriptor.EnumDescriptor(
  name='PokemonMovementType',
  full_name='pogoprotos.enums.PokemonMovementType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENC_MOVEMENT_STATIC', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENC_MOVEMENT_JUMP', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENC_MOVEMENT_VERTICAL', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENC_MOVEMENT_PSYCHIC', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENC_MOVEMENT_ELECTRIC', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENC_MOVEMENT_FLYING', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='POKEMON_ENC_MOVEMENT_HOVERING', index=6, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=67,
  serialized_end=324,
)
_sym_db.RegisterEnumDescriptor(_POKEMONMOVEMENTTYPE)

PokemonMovementType = enum_type_wrapper.EnumTypeWrapper(_POKEMONMOVEMENTTYPE)
POKEMON_ENC_MOVEMENT_STATIC = 0
POKEMON_ENC_MOVEMENT_JUMP = 1
POKEMON_ENC_MOVEMENT_VERTICAL = 2
POKEMON_ENC_MOVEMENT_PSYCHIC = 3
POKEMON_ENC_MOVEMENT_ELECTRIC = 4
POKEMON_ENC_MOVEMENT_FLYING = 5
POKEMON_ENC_MOVEMENT_HOVERING = 6


DESCRIPTOR.enum_types_by_name['PokemonMovementType'] = _POKEMONMOVEMENTTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
