# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/requests/messages/get_map_objects_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/requests/messages/get_map_objects_message.proto',
  package='pogoprotos.networking.requests.messages',
  syntax='proto3',
  serialized_pb=_b('\nEpogoprotos/networking/requests/messages/get_map_objects_message.proto\x12\'pogoprotos.networking.requests.messages\"f\n\x14GetMapObjectsMessage\x12\x0f\n\x07\x63\x65ll_id\x18\x01 \x03(\x04\x12\x15\n\rsince_time_ms\x18\x02 \x03(\x03\x12\x12\n\nplayer_lat\x18\x03 \x01(\x01\x12\x12\n\nplayer_lng\x18\x04 \x01(\x01\x62\x06proto3')
)




_GETMAPOBJECTSMESSAGE = _descriptor.Descriptor(
  name='GetMapObjectsMessage',
  full_name='pogoprotos.networking.requests.messages.GetMapObjectsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cell_id', full_name='pogoprotos.networking.requests.messages.GetMapObjectsMessage.cell_id', index=0,
      number=1, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='since_time_ms', full_name='pogoprotos.networking.requests.messages.GetMapObjectsMessage.since_time_ms', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_lat', full_name='pogoprotos.networking.requests.messages.GetMapObjectsMessage.player_lat', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_lng', full_name='pogoprotos.networking.requests.messages.GetMapObjectsMessage.player_lng', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=114,
  serialized_end=216,
)

DESCRIPTOR.message_types_by_name['GetMapObjectsMessage'] = _GETMAPOBJECTSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetMapObjectsMessage = _reflection.GeneratedProtocolMessageType('GetMapObjectsMessage', (_message.Message,), dict(
  DESCRIPTOR = _GETMAPOBJECTSMESSAGE,
  __module__ = 'pogoprotos.networking.requests.messages.get_map_objects_message_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.requests.messages.GetMapObjectsMessage)
  ))
_sym_db.RegisterMessage(GetMapObjectsMessage)


# @@protoc_insertion_point(module_scope)
